import { describe, expect, it } from "vitest";
import { poseidon2, poseidon4 } from "poseidon-lite";
import { commitmentField, fieldFromString, hashPair, ZEROES, TREE_DEPTH } from "./poseidon";

// Committed deterministic vector (circuits/vectors.json), generated by
// circuits/make-vectors.mjs from the same relations the circuit enforces.
const VECTOR = {
  root: "17097246353115869061148168610340838857602341774383070978264815864266037186395",
  nullifiers: [
    "4526667789454487704762445668693257540585738291428588147329565298186698332082",
    "17041492087720600691918904253163667295422498708556382438430372228465657129768",
  ],
  outputCommit: [
    "4919994872950763932095563726169675306627372085010227872238879681887022790747",
    "5042773088413423552879952180209454621256470933978214649531057741826086916",
  ],
  domainField: "16408744501190376288954182046482207264388319625399064319593305747664045410440",
};

describe("circuit parity", () => {
  it("uses the same Poseidon as circomlib (BN254)", () => {
    // Reference outputs from circomlib's Poseidon over the same inputs.
    expect(poseidon2([1n, 2n]).toString()).toBe("7853200120776062878684798364095072458815029376092732009249414926327459813530");
    expect(poseidon4([1n, 2n, 3n, 4n]).toString()).toBe("18821383157269793795438455681495246036402687001665670618754263018637548127333");
  });

  it("derives the committed nullifiers from commitments and the spend key", () => {
    const spendKey = fieldFromString("vec-spend-key");
    const c0 = commitmentField(600, 0, fieldFromString("vec-r0"), fieldFromString("vec-owner0"));
    const c1 = commitmentField(500, 0, fieldFromString("vec-r1"), fieldFromString("vec-owner1"));
    expect(poseidon2([c0, spendKey]).toString()).toBe(VECTOR.nullifiers[0]);
    expect(poseidon2([c1, spendKey]).toString()).toBe(VECTOR.nullifiers[1]);
  });

  it("reconstructs the committed Merkle root from two leaves", () => {
    const c0 = commitmentField(600, 0, fieldFromString("vec-r0"), fieldFromString("vec-owner0"));
    const c1 = commitmentField(500, 0, fieldFromString("vec-r1"), fieldFromString("vec-owner1"));
    let cur = hashPair(c0.toString(), c1.toString());
    for (let d = 1; d < TREE_DEPTH; d++) cur = hashPair(cur, ZEROES[d]);
    expect(cur).toBe(VECTOR.root);
  });

  it("derives the committed output commitments and domain field", () => {
    expect(commitmentField(480, 0, fieldFromString("vec-out0"), fieldFromString("vec-recv")).toString()).toBe(VECTOR.outputCommit[0]);
    expect(commitmentField(600, 0, fieldFromString("vec-out1"), fieldFromString("vec-owner1")).toString()).toBe(VECTOR.outputCommit[1]);
    expect(fieldFromString("transfer:vec").toString()).toBe(VECTOR.domainField);
  });
});
