// Generate real, reproducible circuit vectors against the committed artifacts.
//
//   node circuits/make-vectors.mjs
//
// Uses the same field mapping the app uses (src/lib/poseidon.ts): strings are
// mapped into Fr by sha256, commitments are Poseidon4(value, assetId, rField,
// ownerField), nullifiers are Poseidon2(commitment, spendKey), and tree nodes
// are Poseidon2(left, right). It builds a small depth-20 tree, produces a real
// Groth16 proof, verifies it, then writes circuits/vectors.json.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { poseidon2, poseidon4 } from "poseidon-lite";
import * as snarkjs from "snarkjs";

const FIELD = 21888242871839275222246405745257275088548364400416034343698204186575808495617n;
const DEPTH = 20;
const fieldFromString = (s) => BigInt("0x" + createHash("sha256").update("kilnen-field-v1:" + s).digest("hex")) % FIELD;
const commitmentFor = (value, assetId, r, owner) => poseidon4([BigInt(value), BigInt(assetId), fieldFromString(r), fieldFromString(owner)]).toString();
const nullifierFor = (commitment, spendKey) => poseidon2([BigInt(commitment), BigInt(spendKey)]).toString();
const hashPair = (l, r) => poseidon2([BigInt(l), BigInt(r)]).toString();

const ZEROES = ["0"];
for (let i = 0; i < DEPTH; i++) ZEROES.push(hashPair(ZEROES[i], ZEROES[i]));

function pathFor(leaves, index) {
  const siblings = [];
  const pathIndices = [];
  let idx = index;
  const level = leaves.slice();
  for (let d = 0; d < DEPTH; d++) {
    const siblingIndex = idx ^ 1;
    siblings.push(level[siblingIndex] ?? ZEROES[d]);
    pathIndices.push(idx % 2);
    const next = [];
    for (let i = 0; i < level.length; i += 2) next.push(hashPair(level[i] ?? ZEROES[d], level[i + 1] ?? ZEROES[d]));
    level.length = 0;
    level.push(...next);
    idx = Math.floor(idx / 2);
  }
  // root: fold the leaf up
  let cur = leaves[index];
  idx = index;
  for (let d = 0; d < DEPTH; d++) {
    cur = idx % 2 === 0 ? hashPair(cur, siblings[d]) : hashPair(siblings[d], cur);
    idx = Math.floor(idx / 2);
  }
  return { siblings, pathIndices, root: cur };
}

async function main() {
  const spendKey = fieldFromString("vec-spend-key").toString();
  const assetId = "0";
  const inValue = [600n, 500n];
  const inR = ["vec-r0", "vec-r1"];
  const inOwner = ["vec-owner0", "vec-owner1"];
  const c0 = commitmentFor(inValue[0], assetId, inR[0], inOwner[0]);
  const c1 = commitmentFor(inValue[1], assetId, inR[1], inOwner[1]);

  const leaves = [c0, c1];
  const p0 = pathFor(leaves, 0);
  const p1 = pathFor(leaves, 1);
  if (p0.root !== p1.root) throw new Error("root mismatch");

  const feeTokens = 20n;
  const relayerFee = 0n;
  const outValue = [480n, inValue[0] + inValue[1] - 480n - feeTokens - relayerFee];
  const outR = ["vec-out0", "vec-out1"];
  const outOwner = ["vec-recv", "vec-owner1"];
  const outputCommit = [
    commitmentFor(outValue[0], assetId, outR[0], outOwner[0]),
    commitmentFor(outValue[1], assetId, outR[1], outOwner[1]),
  ];
  const nullifier = [nullifierFor(c0, spendKey), nullifierFor(c1, spendKey)];
  const domain = fieldFromString("transfer:vec").toString();

  const input = {
    root: p0.root,
    nullifier,
    outputCommit,
    assetId,
    feeTokens: feeTokens.toString(),
    relayerFee: relayerFee.toString(),
    domain,
    inValue: inValue.map(String),
    inR: inR.map((s) => fieldFromString(s).toString()),
    inOwner: inOwner.map((s) => fieldFromString(s).toString()),
    spendKey,
    pathElements: [p0.siblings, p1.siblings],
    pathIndices: [p0.pathIndices, p1.pathIndices],
    outValue: outValue.map(String),
    outR: outR.map((s) => fieldFromString(s).toString()),
    outOwner: outOwner.map((s) => fieldFromString(s).toString()),
  };

  const wasm = "circuits/build/kilnen-spend_js/kilnen-spend.wasm";
  const zkey = "circuits/build/kilnen-spend.zkey";
  const { proof, publicSignals } = await snarkjs.groth16.fullProve(input, wasm, zkey);
  const vkey = JSON.parse(readFileSync("circuits/verification_key.json", "utf8"));
  const ok = await snarkjs.groth16.verify(vkey, publicSignals, proof);
  if (!ok) throw new Error("real proof failed verification — artifacts inconsistent");

  const vectors = {
    note: "REAL Groth16 vectors generated by circuits/setup.sh + make-vectors.mjs. Proven and verified against the committed verification key; do not hand-edit.",
    circuitId: "kilnen-joinsplit-v1",
    depth: DEPTH,
    assetId: Number(assetId),
    feeTokens: Number(feeTokens),
    relayerFee: Number(relayerFee),
    root: p0.root,
    nullifiers: nullifier,
    outputCommit,
    domainField: domain,
    input,
    publicSignals,
  };
  writeFileSync("circuits/vectors.json", JSON.stringify(vectors, null, 2) + "\n");
  console.log("verified=true publicSignals=", publicSignals.length);
  console.log("root=", p0.root);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
